openapi: 3.0.0
info:
  title: LearnerWiz API
  description: API for user registration, login, and language content management
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local server
paths:
  /:
    get:
      summary: Home Page of the application
      tags:
        - Home
      responses:
        '200':
          description: Home page
          content:
            text/html:
              schema:
                type: string
  /login:
    get:
      summary: Render Login Page of the application
      tags:
        - User Management
      responses:
        '200':
          description: Login Page
          content:
            text/html:
              schema:
                type: string
    post:
      summary: Login an existing user
      tags:
        - User Management
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'
      responses:
        '200':
          description: Successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: JWT Access Token for authentication
  /register:
    get:
      summary: Render Register Page of the application
      tags:
        - User Management
      responses:
        '200':
          description: Register Page
          content:
            text/html:
              schema:
                type: string
    post:
      summary: Register a new user
      tags:
        - User Management
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUser'
      responses:
        '200':
          description: Successfully registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: Messge indicating successful registration
  /logout:
    get:
      summary: Logout user
      tags:
        - User Management
      responses:
        '200':
          description: Successfully Logged out
          content:
            text/html:
              schema:
                type: string
  /leaderboard:
    get:
      summary: Leaderboard
      tags:
        - Leaderboard
      responses:
        '200':
          description: Leaderboard
          content:
            text/html:
              schema:
                type: string
  /dashboard:
    get:
      summary: Dashboard
      tags:
        - Dashboard
      responses:
        '200':
          description: Dashboard of the user
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Error while processing data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerFailure'
  /language/{languageId}:
    get:
      summary: Get Language contents
      tags:
        - Language Content
      responses:
        '200':
          description: Learning language of the user
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Fetching contents of the language failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerFailure'
  /language/{languageId}/{wordId}:
    post:
      summary: Mark word as complete
      tags:
        - Language Content
      requiredBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WordComplete'
      responses:
        '200':
          description: Successfully completed the word
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Mapping user with word failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerFailure'
components:
  schemas:
    ServerFailure:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Internal Server Error
    WordComplete:
      type: object
      required:
        - username
        - languageId
        - wordId
      properties:
        username:
          type: string
          description: Username of the user
        languageId:
          type: string
          description: ID of the selected Language
        wordId:
          type: string
          description: ID of the completed Word
    RegisterUser:
      type: object
      required:
        - username
        - email
        - password
      properties:
        username:
          type: string
          description: Username of the user
        email:
          type: string
          format: email
          description: Email address of the user
        password:
          type: string
          format: password
          description: Password of the user
    LoginUser:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: Email address of the user
        password:
          type: string
          format: password
          description: Password of the user
    LanguageContentResponse:
      type: object
      properties:
        code:
          type: string
          description: The code of the language.
        languageId:
          type: integer
          description: The ID of the language.
        content:
          type: array
          items:
            type: object
            properties:
              wordId:
                type: integer
                description: The ID of the word.
              word:
                type: string
                description: The word in the language.
              translation:
                type: string
                description: The translation of the word.
              meaning:
                type: string
                description: The meaning of the word.
              progress:
                type: integer
                description: Progress of the word for the user (0 or 1).
    LanguageResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
                description: language code
              languageId:
                type: integer
                description: The ID of the word.
              progress:
                type: integer
                description: Progress of the word for the user (0 or 1).
